-- Independent Tables (No Foreign Keys)
CREATE TABLE Member_type (
    member_type_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name      VARCHAR2(50) NOT NULL,
    member_fee     NUMBER(10, 2) DEFAULT 0.00,
    CONSTRAINT chk_member_fee CHECK (member_fee >= 0)
);

CREATE TABLE Food_category (
    cat_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(100) NOT NULL
);

CREATE TABLE Voucher (
    voucher_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_name   VARCHAR2(100) NOT NULL,
    discount_value NUMBER(10, 2) NOT NULL,
    min_spend      NUMBER(10, 2) DEFAULT 0.00,
    start_date      DATE NOT NULL,
    end_date       DATE NOT NULL
);

CREATE TABLE Delivery_company (
    delivery_company_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name        VARCHAR2(100) NOT NULL,
    delivery_charge     NUMBER(10, 2) DEFAULT 0.00
);

CREATE TABLE Receipt (
    receipt_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subtotal      NUMBER(10, 2) NOT NULL,
    discount_amt  NUMBER(10, 2) DEFAULT 0.00,
    delivery_fee  NUMBER(10, 2) DEFAULT 0.00,
    grand_total   NUMBER(10, 2) NOT NULL,
    creation_date DATE DEFAULT SYSDATE
);

--Referencing Tables (With Foreign Keys)
CREATE TABLE Member (
    member_id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_type_id    NUMBER(10) NOT NULL,
    member_name       VARCHAR2(255) NOT NULL,
    email             VARCHAR2(255) UNIQUE NOT NULL,
    phone             VARCHAR2(20),
    birth_date        DATE,
    registration_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_member_type FOREIGN KEY (member_type_id) REFERENCES Member_type(member_type_id)
);

CREATE TABLE Restaurant (
    restaurant_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_name VARCHAR2(255) NOT NULL,
    is_halal        NUMBER(1) DEFAULT 0, -- 0=False, 1=True
    location        VARCHAR2(500) NOT NULL,
    operating_hour  VARCHAR2(100) NOT NULL,
    rating          NUMBER(2, 1),
    is_active       NUMBER(1) DEFAULT 1,
    CONSTRAINT chk_rest_halal  CHECK (is_halal IN (0, 1)), -- Constraint to ensure is_halal is either 0 or 1
    CONSTRAINT chk_rest_active CHECK (is_active IN (0, 1)), -- Constraint to ensure is_active is either 0 or 1
    CONSTRAINT chk_rest_rating CHECK (rating BETWEEN 0 AND 5) -- Constraint to ensure rating is between 0 and 5
);

CREATE TABLE Delivery_address (
    address_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    NUMBER(10) NOT NULL,
    address_type VARCHAR2(50), 
    full_address VARCHAR2(1000) NOT NULL,
    is_default   NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_addr_member FOREIGN KEY (member_id) REFERENCES Member(member_id),
    CONSTRAINT chk_addr_def   CHECK (is_default IN (0, 1))
);

CREATE TABLE Restaurant_food (
    restaurant_food_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id      NUMBER(10) NOT NULL,
    cat_id             NUMBER(10) NOT NULL,
    food_name          VARCHAR2(255) NOT NULL,
    current_price      NUMBER(10, 2) NOT NULL,
    old_price          NUMBER(10, 2), 
    new_price          NUMBER(10, 2),
    is_super_deal      NUMBER(1) DEFAULT 0,
    is_budget_meal     NUMBER(1) DEFAULT 0,
    is_available       NUMBER(1) DEFAULT 1,
    description        VARCHAR2(1000),
    CONSTRAINT fk_food_rest    FOREIGN KEY (restaurant_id) REFERENCES Restaurant(restaurant_id),
    CONSTRAINT fk_food_cat     FOREIGN KEY (cat_id) REFERENCES Food_category(cat_id),
    CONSTRAINT chk_food_super  CHECK (is_super_deal IN (0, 1)),
    CONSTRAINT chk_food_budget CHECK (is_budget_meal IN (0, 1)),
    CONSTRAINT chk_food_avail  CHECK (is_available IN (0, 1))
);

CREATE TABLE Member_voucher (
    member_voucher_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id        NUMBER(10) NOT NULL,
    member_id         NUMBER(10) NOT NULL,
    date_received     DATE DEFAULT SYSDATE,
    is_used           NUMBER(1) DEFAULT 0,
    date_used         DATE,
    voucher_desc      VARCHAR2(500),
    CONSTRAINT fk_mv_vouch FOREIGN KEY (voucher_id) REFERENCES Voucher(voucher_id),
    CONSTRAINT fk_mv_mem   FOREIGN KEY (member_id) REFERENCES Member(member_id),
    CONSTRAINT chk_mv_used CHECK (is_used IN (0, 1))
);

CREATE TABLE Payment (
    payment_id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id       NUMBER(10) UNIQUE NOT NULL,
    payment_method   VARCHAR2(50),
    payment_status   VARCHAR2(50),
    transaction_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_pay_receipt FOREIGN KEY (receipt_id) REFERENCES Receipt(receipt_id)
);

-- Create Delivery_service first without order_id constraint
CREATE TABLE Delivery_service (
    service_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            NUMBER(10), 
    delivery_company_id NUMBER(10) NOT NULL,
    address_id          NUMBER(10) NOT NULL,
    delivery_type       VARCHAR2(50),
    CONSTRAINT chk_ds_type CHECK (delivery_type IN ('Delivery', 'Pickup')),
    CONSTRAINT fk_ds_company FOREIGN KEY (delivery_company_id) REFERENCES Delivery_company(delivery_company_id),
    CONSTRAINT fk_ds_address FOREIGN KEY (address_id) REFERENCES Delivery_address(address_id)
);

-- Create Orders with NULLABLE service_id to allow for Pickup
CREATE TABLE Orders (
    order_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id         NUMBER(10) NOT NULL,
    service_id        NUMBER(10), -- NULL = Pickup
    restaurant_id     NUMBER(10) NOT NULL,
    member_voucher_id NUMBER(10),
    payment_id        NUMBER(10) UNIQUE NOT NULL,
    total_item_qty    NUMBER(5),
    order_date        DATE DEFAULT SYSDATE,
    order_status      VARCHAR2(50),
    CONSTRAINT fk_ord_member FOREIGN KEY (member_id) REFERENCES Member(member_id),
    CONSTRAINT fk_ord_service FOREIGN KEY (service_id) REFERENCES Delivery_service(service_id),
    CONSTRAINT fk_ord_rest    FOREIGN KEY (restaurant_id) REFERENCES Restaurant(restaurant_id), 
    CONSTRAINT fk_ord_vouch   FOREIGN KEY (member_voucher_id) REFERENCES Member_voucher(member_voucher_id),
    CONSTRAINT fk_ord_pay     FOREIGN KEY (payment_id) REFERENCES Payment(payment_id)
);

-- Add the missing link back to Orders to finish the circular structure
ALTER TABLE Delivery_service ADD CONSTRAINT fk_ds_order FOREIGN KEY (order_id) REFERENCES Orders(order_id);

CREATE TABLE Order_food (
    order_food_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           NUMBER(10) NOT NULL,
    restaurant_food_id NUMBER(10) NOT NULL,
    quantity           NUMBER(5) DEFAULT 1,
    unit_price         NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_of_order FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    CONSTRAINT fk_of_food  FOREIGN KEY (restaurant_food_id) REFERENCES Restaurant_food(restaurant_food_id)
);